pinentry-program /usr/bin/pinentry

no-allow-external-cache
no-allow-loopback-pinentry
no-allow-mark-trusted

# Cache passphrases
default-cache-ttl 600
max-cache-ttl 7200

# SSH
enable-ssh-support
default-cache-ttl-ssh 1800
max-cache-ttl-ssh 7200
