with-fingerprint
with-subkey-fingerprint
list-options show-uid-validity
keyid-format 0xlong

# trust
trust-model tofu+pgp
tofu-default-policy unknown

require-secmem
no-auto-key-retrieve
no-auto-key-import
no-auto-trust-new-key

# algos
disable-cipher-algo 3DES DES
