---
- hosts: all
  gather_facts: true
  vars:
    features: "{{ (lookup('pipe', 'chezmoi data') | from_yaml).features }}"
  roles:
    - base
    - gcc
    - role: liquidprompt
      when: features.cli
