---
- hosts: all
  gather_facts: true
  vars:
    features: "{{ (lookup('pipe', 'chezmoi data') | from_yaml).features }}"
    flatpak_method: user
  roles:
    - base
    - gcc
    - liquidprompt
    - hyx
    - role: flatpak
      when: features.gui
